webdriver {
  driver = chrome
  autodownload = true
  base.url = "https://www.saucedemo.com"
  timeouts {
    implicitlywait = 5000
  }
}

serenity {
  project.name = "Reto Tecnico QA Frontend"
  take.screenshots = FOR_FAILURES
  report.encoding = UTF-8
}

chrome.switches = "--start-maximized;--disable-infobars;--disable-popup-blocking"
